@host = localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFtYW5hIFB1dHJhIiwiYWRtaW4iOnRydWUsImV4cCI6MTY5NjUzMTc0M30.76VPlOPSth5q7CGPU1B9XIL8OXyHzLwV4-H0ymOzvsM

///////////////////
// Restricted Area
///////////////////

// Create Product
POST http://{{host}}/product HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
   
{
    "name": "test-product",
    "description": "random-description",
    "price": 1020.00
}

###

// Get Product By ID
GET http://{{host}}/product/4 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###

// Get All Products
GET http://{{host}}/product/with/count HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###

// Update Product
PUT http://{{host}}/product/6 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "updated-product",
    "description": "random-description-updated",
    "price": 1030.00
}

###

// Delete Product
DELETE http://{{host}}/product/6 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
    
